spring.application.name=sms-sender
server.port=8081
# Kafka Server
spring.kafka.bootstrap-servers=localhost:9092

# Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Topic name (custom)
kafka.topic.name=sms-topic